export const commonConst={
    params_tablename:"tablename",
    params_tablename_instance:"tablename_instance",
    params_tablename_to_preview:"data",
    params_tablename_index:"activeIndex",
    params_pageNation:"pageNation",
    params_id:"id",
    params_staging:"staging",
    params_schema_data:"schema-data",
    params_layer_Name:"layer_Name",
    params_source:"source",
    userData:"userData",
    JWT:"token",
    get:"get",
    login:'login',
    register:'register',
    userName:"username",
    bearer: "Bearer",
    translate_en:"en",
    translate_fr:"fr",
    modal_size_xl:"xl",
    modal_size_lg: "lg",
    modal_backdrop_static:"static",
    auditUrl:'/api/audit/',
    airByte:"_AIRBYTE",
    system:"SYSTEM",
    selectColumns:"selected_columns",
    UnknownError:"Unknown Error",
    httpAcceptHeader:"application/json",
    rulevalidation: "ruleValidation",
    error: "error",
    getColumns: "get_columns",
    spotlight_hash:"_SPOTLIGHT_HASHID"
}